Repository Kernel-GL-HRK/gl-kernel-basecamp-2019, pull requests merged in 2019-03, with the labels that each got.

#14 Lesson01: Implement first part of task - "Guess the Number" game
  .gitignore
  01-Git_Bash_Make/guess.c
Labels: OK, ready

#17 Lesson01: Implement first part of task - "Guess the Number" game
  01-Git_Bash_Make/main.c
Labels: OK

#16 Lesson02 HW
  01-Git_Bash_Make/guess_number.c
Labels: OK

#31 Lesson 3 part 2: Implementation bash script
  01-Git_Bash_Make/release/guesanumber.tar.gz
  01-Git_Bash_Make/script.sh
Labels: OK

#33 Lesson01-Bash: Implement second part of task - bash script with basic commands
  01-Git_Bash_Make/release/guessanumber.tar.gz
  01-Git_Bash_Make/script.sh
Labels: OK

#28 Task1_Game
  01-Git_Bash_Make/Task1_game/.gitignore
  01-Git_Bash_Make/Task1_game/main.c
Labels: OK

#26 Irina anokhina
  01-Git_Bash_Make/game.cpp
Labels: changes requested, ready

#7 Complete first task of lesson 2
  01-Git_Bash_Make/guessNumber.cpp
Labels: OK

#19 First home task
  01-Git_Bash_Make/checkpatch.pl
  01-Git_Bash_Make/main.c
Labels: OK

#35 Lesson 2 Part 1: Random number game
  01-Git_Bash_Make/random_game.c
Labels: OK

#37 Game “Guess a number”
  01-Git_Bash_Make/guess_a_number.c
Labels: OK

#20 Implementation of "Random game"
  01-Git_Bash_Make/.gitignore
  01-Git_Bash_Make/HW1.cpp
Labels: OK

#27 Game in randome numbers
  Task1/main.c
Labels: OK

#38 Implement "Random Game"
  01-Git_Bash_Make/main.c
Labels: OK

#43 Lesson02
  01-Git_Bash_Make/guess_a_number/main.c
Labels: OK

#12 Lesson 2 Part 1: Simple game “guess a number”
  01-Git_Bash_Make/homework01.c
Labels: OK

#42 Lesson 1. "Random game" implementation
  01-Git_Bash_Make/a.out
  01-Git_Bash_Make/randomGame.c
Labels: OK

#51 Lesson 2 Part 1: Add number guess feature
  01-Git_Bash_Make/.gitignore
  01-Git_Bash_Make/main
  01-Git_Bash_Make/main.c
Labels: OK

#57 Lesson 2 Part 2: Create comressing bash script
  01-Git_Bash_Make/compressScript.sh
Labels: OK

#56 Developer kalynenko
  Hometask/.gitignore
  Hometask/Readme.txt
  Hometask/main.cc
Labels: OK

#54 Lesson 4 Part 3: Implementation automatic build project
  01-Git_Bash_Make/Makefile
  01-Git_Bash_Make/guesanumber.c
  01-Git_Bash_Make/guesanumber.h
  01-Git_Bash_Make/main.c
Labels: OK

#61 Implementation of bash script
  01-Git_Bash_Make/bashscript.sh
  01-Git_Bash_Make/game/main.c
  01-Git_Bash_Make/release/game.tar.gz
Labels: OK

#69 Lesson01-Make: Implement third part of task - makefile for project building
  01-Git_Bash_Make/Makefile
  01-Git_Bash_Make/guess.c
  01-Git_Bash_Make/guess.h
  01-Git_Bash_Make/main.c
Labels: OK

#60 Lesson 2 Part 3: Create makefile
  01-Git_Bash_Make/Makefile
  01-Git_Bash_Make/guessCheck.cpp
  01-Git_Bash_Make/guessCheck.h
  01-Git_Bash_Make/guessNumber.cpp
Labels: OK

#64 Lesson 3 Part 2: Bash
  01-Git_Bash_Make/script.sh
Labels: OK

#75 Lesson 4 Part 3: Make
  01-Git_Bash_Make/guess_game.c
  01-Git_Bash_Make/guess_game.h
  01-Git_Bash_Make/main.c
  01-Git_Bash_Make/makefile
Labels: OK

#68 Imlementation of makefile
  01-Git_Bash_Make/guesanumber.c
  01-Git_Bash_Make/guesanumber.h
  01-Git_Bash_Make/main.c
  01-Git_Bash_Make/makefile
Labels: OK

#77 Lesson 2-4 part 2-3
  01-Git_Bash_Make/guess_a_number/Makefile
  01-Git_Bash_Make/guess_a_number/compress.sh
  01-Git_Bash_Make/guess_a_number/lib.c
  01-Git_Bash_Make/guess_a_number/lib.h
  01-Git_Bash_Make/guess_a_number/main.c
Labels: OK

#47 Lesson02
  01-Git_Bash_Make/dz1.c
Labels: OK

#79 Lesson 3 Part 2: Bash script
  01-Git_Bash_Make/Task2_bash_script/script.sh
Labels: OK

#76 Lesson 03 - Bash: Creating bash script
  01-Git_Bash_Make/script.sh
Labels: OK

#58 Lesson 02 Part 01: Create "Guess a Number" game
  01-Git_Bash_Make/guessanumber.c
Labels: OK

#67 Lesson 2-4 Part 2: Compress script
  01-Git_Bash_Make/script_compress
Labels: OK

#70 Lesson 3 Part 2: Bash script
  01-Git_Bash_Make/script.sh
Labels: OK

#78 Lesson 4 Part 3: Makefile
  01-Git_Bash_Make/.gitignore
  01-Git_Bash_Make/HW1.cpp
  01-Git_Bash_Make/HW1.hpp
  01-Git_Bash_Make/Makefile
Labels: OK

#81 Lesson 04 - Make: Creating make file
  01-Git_Bash_Make/Makefile
  01-Git_Bash_Make/game_code.c
  01-Git_Bash_Make/game_code.h
  01-Git_Bash_Make/random_game.c
Labels: OK

#82 Homework#2-Kalynenko
  Hometask/Myscript.sh
Labels: OK

#80 Lesson 2-4 Part 2: Bash script
  01-Git_Bash_Make/script.sh
Labels: OK

#84 Lesson 4 Part 3: makefile
  01-Git_Bash_Make/Task3_makefile/func.c
  01-Git_Bash_Make/Task3_makefile/func.h
  01-Git_Bash_Make/Task3_makefile/main.c
  01-Git_Bash_Make/Task3_makefile/makefile
Labels: OK

#74 Lesson 03 Part 02: Create Bash script
  01-Git_Bash_Make/Bash_o_script.script
Labels: OK

#86 Homework#3Kalynenko
  Hometask/main.cpp
  Hometask/release/guesanumber.tar.gz
  Homework3/Check.cpp
  Homework3/Check.h
  Homework3/Check.o
  Homework3/InputData.cpp
  Homework3/InputData.h
  Homework3/InputData.o
  Homework3/main.cpp
  Homework3/main.o
  Homework3/makefile
  Homework3/prog
Labels: OK
