Repository Kernel-GL-HRK/gl-kernel-basecamp-2019, pull requests merged in 2019-04, with the labels that each got.

#87 Lesson 2-4 Part 3: Make
  01-Git_Bash_Make/HW3/game.c
  01-Git_Bash_Make/HW3/game.h
  01-Git_Bash_Make/HW3/main.c
  01-Git_Bash_Make/HW3/makefile
Labels: OK

#73 Lesson 03-04 Bash, Make
  01-Git_Bash_Make/Makefile
  01-Git_Bash_Make/main
  01-Git_Bash_Make/main.c
  01-Git_Bash_Make/random.c
  01-Git_Bash_Make/random.h
  01-Git_Bash_Make/script
Labels: OK

#85 Lesson 04 Part 03: Make
  01-Git_Bash_Make/Makefile
  01-Git_Bash_Make/guessanumber.c
  01-Git_Bash_Make/header.h
  01-Git_Bash_Make/main.c
Labels: OK

#90 Lesson 2 Part 3: Make
  01-Git_Bash_Make/Makefile
  01-Git_Bash_Make/fun.c
  01-Git_Bash_Make/fun.h
  01-Git_Bash_Make/homework01.c
Labels: OK

#94 Lesson 2-4 Part 3: Makefile for game “guess a number”
  01-Git_Bash_Make/Makefile
  01-Git_Bash_Make/generator.c
  01-Git_Bash_Make/generator.h
  01-Git_Bash_Make/guess_a_number.c
Labels: OK

#97 Lesson 4 part 3: Makefile.
  Makefile
  Second.c
  main.c
Labels: OK

#83 Lesson 3 part 2: Bash Script
  script.sh
Labels: OK

#66 Lesson 2 Part 2: Bash script
  01-Git_Bash_Make/scriptTar.sh
Labels: OK

#96 Homework01.part03
  01-Git_Bash_Make/Makefile
  01-Git_Bash_Make/dz1.c
  01-Git_Bash_Make/game.c
  01-Git_Bash_Make/game.h
Labels: OK

#102 Lesson 02: Implementing a character device
  02-KernelModules_CharacterDevice/Makefile
  02-KernelModules_CharacterDevice/Testing.md
  02-KernelModules_CharacterDevice/concdev.c
  02-KernelModules_CharacterDevice/concdev.h
  02-KernelModules_CharacterDevice/concmod.c
  02-KernelModules_CharacterDevice/proc_info.c
  02-KernelModules_CharacterDevice/proc_info.h
  02-KernelModules_CharacterDevice/sysfs_control.c
  02-KernelModules_CharacterDevice/sysfs_control.h
  02-KernelModules_CharacterDevice/test.sh
Labels: good first issue, ready

#105 Lesson 5-7: Simple character device
  02-KernelModules_CharacterDevice/Makefile
  02-KernelModules_CharacterDevice/TestingScenario.md
  02-KernelModules_CharacterDevice/char_device_source.c
  02-KernelModules_CharacterDevice/char_device_test.sh
Labels: ready

#98 Lesson 5-7 p1: Character device
  02-KernelModules_CharacterDevice/Makefile
  02-KernelModules_CharacterDevice/chrdev.c
Labels: OK

#112 Lesson 1: Task1: Simple guess number game
  01-Git_Bash_Make/main.cpp
Labels: OK

#113 Lesson1: Task2: Copying and archiving working directory
  01-Git_Bash_Make/compress.sh
Labels: ready

#119 Lesson 05-07: Character device driver
  02-KernelModules_CharacterDevice/03/MyModuleTest/Makefile
  02-KernelModules_CharacterDevice/03/MyModuleTest/TestInstructions.md
  02-KernelModules_CharacterDevice/03/MyModuleTest/char_driver.c
  02-KernelModules_CharacterDevice/03/MyModuleTest/device_test.sh
Labels: good first issue, ready

#118 Lesson 05-07 : Implement a character device driver for text messaging between users.
  02-KernelModules_CharacterDevice/HOW2.txt
  02-KernelModules_CharacterDevice/Makefile
  02-KernelModules_CharacterDevice/chrdev.c
  02-KernelModules_CharacterDevice/script.sh
Labels: good first issue, ready

#109 Lesson05-07: Implement character device driver with procfs/sysfs interfaces
  02-KernelModules_CharacterDevice/src/Makefile
  02-KernelModules_CharacterDevice/src/intercom.c
  02-KernelModules_CharacterDevice/test/devtest.sh
Labels: OK

#100 Lesson 5-7 p3: test script
  02-KernelModules_CharacterDevice/chrdev.c
  02-KernelModules_CharacterDevice/test-chr-dev.sh
Labels: OK

#101 Lesson 5-7 part 1-3:Chardev +procfs+ sysfs
  02-KernelModules_CharacterDevice/Makefile
  02-KernelModules_CharacterDevice/README.md
  02-KernelModules_CharacterDevice/Scenario
  02-KernelModules_CharacterDevice/chrdev.c
  02-KernelModules_CharacterDevice/testscript.sh
Labels: OK

#111 Lesson 5-7 part 1: Driver
  chtest.c
Labels: ready

#116 Lesson 5-7: Driver for character device
  02-KernelModules_CharacterDevice/Makefile
  02-KernelModules_CharacterDevice/chrdev_driver.c
  02-KernelModules_CharacterDevice/chrdev_driver.h
  02-KernelModules_CharacterDevice/chrdev_driver_test.sh
  02-KernelModules_CharacterDevice/chrdev_test_inst.md
Labels: OK

#123 Lesson 07 Character Device
  02-KernelModules_CharacterDevice/Makefile
  02-KernelModules_CharacterDevice/my_chardev.c
Labels: OK

#115 Lesson 5-7 part 2-3: Test bash script and instruction
  how2
  script.sh
  testrw.c
Labels: OK
